const CACHE='kgpk-v4-mobilefix';
const CORE=['./','./index.html','./manifest.json'];

const MOBILE_PATCH=String.raw`
<style id="kg-mobile-fix-css">
.close{width:40px!important;height:40px!important;border:1px solid #f0b8b4!important;border-radius:50%!important;background:#fff!important;color:#b42318!important;display:grid!important;place-items:center!important;font-size:20px!important;font-weight:800!important;line-height:1!important;box-shadow:0 3px 12px rgba(180,35,24,.08)!important}
@media(max-width:640px){.hero{padding:38px 0 44px!important}.hero h1{font-size:clamp(32px,9.5vw,39px)!important;line-height:1.08!important;letter-spacing:-.7px!important;max-width:340px!important}.hero p{font-size:14px!important;line-height:1.7!important}.accountBtn{display:inline-flex!important;align-items:center!important;gap:8px!important}.accountAvatarWrap{width:28px!important;height:28px!important;border-radius:50%!important;overflow:hidden!important;display:grid!important;place-items:center!important;background:#f7f1e3!important;color:#8b6b2e!important;flex:0 0 28px!important}.accountAvatarWrap img{width:100%!important;height:100%!important;object-fit:cover!important}.accountBtn #accountLabel{max-width:125px!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}.profileAvatar{width:62px;height:62px;border-radius:50%;display:grid;place-items:center;background:#f7f1e3;color:#8b6b2e;border:1px solid #e4d4ad;font-size:24px;overflow:hidden}.profileAvatar img{width:100%;height:100%;object-fit:cover}.customerProfileCard{box-shadow:0 8px 25px rgba(23,23,23,.05)}}
</style>
<script id="kg-mobile-fix-js">
(function(){
const $=s=>document.querySelector(s), esc2=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function accountUI(){const u=window.currentUser,b=$('#accountBtn');if(!b)return;const label=$('#accountLabel')||(()=>{const x=document.createElement('span');x.id='accountLabel';b.appendChild(x);return x})();const wrap=$('#accountAvatarWrap')||(()=>{const x=document.createElement('span');x.id='accountAvatarWrap';x.className='accountAvatarWrap';b.prepend(x);return x})();if(u){b.classList.remove('hidden');label.textContent=u.displayName||u.email?.split('@')[0]||'My Account';wrap.innerHTML=u.photoURL?'<img src="'+esc2(u.photoURL)+'" alt="Profile">':'<i class="fa-regular fa-user"></i>'}}
function addProfile(){const page=$('#page-customer-account'),sum=$('#customerSummary');if(!page||!sum||$('#customerProfileCard'))return;const card=document.createElement('div');card.id='customerProfileCard';card.className='panel customerProfileCard';card.style.marginBottom='15px';card.innerHTML='<div style="display:flex;align-items:center;gap:14px;flex-wrap:wrap"><div id="customerProfileAvatar" class="profileAvatar"><i class="fa-regular fa-user"></i></div><div style="flex:1;min-width:180px"><h3 id="customerProfileName" style="margin:0">Customer Account</h3><div id="customerProfileEmail" class="small muted">Google account</div></div><span class="tag">Firebase Account</span></div><div class="grid grid2" style="margin-top:15px"><div class="field"><label>WhatsApp / Phone</label><input id="profilePhone" type="tel" placeholder="+92 3XX XXXXXXX"></div><div class="field"><label>Address</label><input id="profileAddress" type="text" placeholder="Swat, Pakistan"></div></div><div class="actions" style="margin-top:12px"><button class="gold" id="saveCustomerProfileBtn">Save Profile</button><button class="outline" id="profileSignOutBtn">Sign Out</button></div>';page.insertBefore(card,sum);$('#saveCustomerProfileBtn').onclick=saveProfile;$('#profileSignOutBtn').onclick=()=>window.handleLogout?.()}
async function loadProfile(){addProfile();const u=window.currentUser;if(!u)return;try{const s=await window.db.ref('users/'+u.uid).once('value'),d=s.val()||{};$('#customerProfileName').textContent=d.name||u.displayName||u.email?.split('@')[0]||'Customer';$('#customerProfileEmail').textContent=d.email||u.email||'';$('#profilePhone').value=d.phone||d.whatsapp||'';$('#profileAddress').value=d.address||'';$('#customerProfileAvatar').innerHTML=u.photoURL?'<img src="'+esc2(u.photoURL)+'" alt="Profile photo">':'<i class="fa-regular fa-user"></i>'}catch(e){console.warn('profile load',e)}}
async function saveProfile(){const u=window.currentUser;if(!u)return window.openLoginModal?.();try{const phone=$('#profilePhone').value.trim(),address=$('#profileAddress').value.trim();await window.db.ref('users/'+u.uid).update({uid:u.uid,name:u.displayName||u.email?.split('@')[0]||'Customer',email:u.email||'',photoURL:u.photoURL||'',phone,whatsapp:phone,address,profileUpdatedAt:Date.now(),role:window.isOwnerUser?'owner':'customer'});window.toast?.('Profile save ho gaya.')}catch(e){console.error(e);window.toast?.('Profile save nahi ho saka. Firebase permissions check karein.',true)}}
const oldApply=window.applyOwnerUI;window.applyOwnerUI=function(){try{oldApply?.()}catch(e){}accountUI();loadProfile()};
const oldShow=window.showPage;const stack=['home'];window.showPage=function(id){const cur=(document.querySelector('.page:not(.hidden)')?.id||'page-home').replace(/^page-/,'');if(id!==cur)stack.push(id);oldShow?.(id);if(id==='customer-account')setTimeout(loadProfile,120)};
function back(){const modal=[...document.querySelectorAll('.modal.show')].reverse()[0];if(modal){window.closeModal?.(modal.id);return true}if(stack.length>1){stack.pop();oldShow?.(stack[stack.length-1]);return true}return false}
let sx=0,sy=0;document.addEventListener('touchstart',e=>{if(e.touches.length===1){sx=e.touches[0].clientX;sy=e.touches[0].clientY}},{passive:true});document.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy,tag=(e.target?.tagName||'').toLowerCase();if(dx>110&&Math.abs(dy)<65&&!['input','textarea','select','button'].includes(tag))back()},{passive:true});
window.startCamera=async function(){try{const video=$('#camera');if(!video)return window.toast?.('Camera preview missing.',true);if(!window.isSecureContext)return window.toast?.('Camera ke liye HTTPS page zaroori hai.',true);if(!navigator.mediaDevices?.getUserMedia)return window.toast?.('Is browser mein camera supported nahi hai.',true);window.stopCamera?.();window.cameraStream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});video.srcObject=window.cameraStream;video.muted=true;video.setAttribute('playsinline','');video.classList.remove('hidden');$('#roomImage')?.classList.add('hidden');$('#roomVideo')?.classList.add('hidden');$('#roomPlaceholder')?.classList.add('hidden');await video.play().catch(()=>{});window.toast?.('Camera preview active')}catch(e){const n=e?.name||'';let m='Camera open nahi hui.';if(n==='NotAllowedError'||n==='PermissionDeniedError')m='Camera permission deny hai. Chrome Settings > Site settings > Camera mein Allow karein.';else if(n==='NotReadableError')m='Camera kisi aur app mein use ho raha hai. Pehle doosri camera/video app band karein.';else if(n==='NotFoundError')m='Phone ka camera available nahi mila.';window.toast?.(m,true)}};
function ready(){accountUI();addProfile();if(window.currentUser)loadProfile()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();setTimeout(ready,800);setTimeout(ready,2000);
})();
</script>`;

self.addEventListener('install',event=>{event.waitUntil((async()=>{const cache=await caches.open(CACHE);for(const url of CORE){try{const request=new Request(url,{cache:'reload'}),response=await fetch(request);if(response.ok)await cache.put(url,response)}catch(_){}}await self.skipWaiting()})())});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('kgpk-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim()})())});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;if(event.request.mode==='navigate'){event.respondWith((async()=>{try{const response=await fetch(event.request,{cache:'no-store'});const html=await response.clone().text();const patched=html.replace('</body>',MOBILE_PATCH+'</body>');const cache=await caches.open(CACHE);await cache.put('./index.html',new Response(patched,{headers:response.headers,status:response.status,statusText:response.statusText}));return new Response(patched,{headers:response.headers,status:response.status,statusText:response.statusText})}catch(_){return(await caches.match('./index.html'))||Response.error()}})());return}event.respondWith((async()=>{const cached=await caches.match(event.request);if(cached)return cached;try{const response=await fetch(event.request);if(response.ok&&new URL(event.request.url).origin===self.location.origin){const cache=await caches.open(CACHE);cache.put(event.request,response.clone())}return response}catch(_){return Response.error()}})())});
